const API_VERSION = "v1";
const MAX_REVIEW_LENGTH = 3;
const JWT_ACCESS_EXPIRATION = 7200; // ? 2 hour 7200
const JWT_REFRESH_EXPIRATION = "3d"; // ? 3 days 3d
// const JWT_ACCESS_EXPIRATION = "15s"; // ? 2 Detik
// const JWT_REFRESH_EXPIRATION = "25s"; // ? 10 Detik
const JWT_EMAIL_EXPIRATION = "1d";
const MAX_IMAGE_ALLOWED = 10;

module.exports = {
  API_VERSION,
  MAX_REVIEW_LENGTH,
  MAX_IMAGE_ALLOWED,
  JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_EXPIRATION,
  JWT_EMAIL_EXPIRATION,
};
