const API_VERSION = "v1";
const MAX_REVIEW_LENGTH = 3;
const JWT_ACCESS_EXPIRATION = 7200; // ? 2 hour 7200
const JWT_REFRESH_EXPIRATION = "3d"; // ? 3 days 3d

module.exports = {
  API_VERSION,
  MAX_REVIEW_LENGTH,
  JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_EXPIRATION,
};
